### ISSUE TITLE
Update and rebuild?

### ISSUE THREAD

**Issue by aldanor** [conda-forge/structlog-feedstock#3]
@vamega Hi! Wondering if you could please trigger an update & rebuild for this?

The build is missing for Python 3.6 and the latest version is now 17.2.0.

Thanks!

**Comment by vamega** [comment]
Hi @aldanor, could you submit a pull request with the updated version. Don't think I'll be able to get to doing this for at least a week despite it being a small change.

Let me know if you need any help in doing so.

**Comment by aldanor** [comment]
Closed in favor of #4

**Comment by aldanor** [comment]
@vamega PR done, would appreciate it if you merged it - thanks.
